server.port=8081
spring.datasource.url=jdbc:postgresql://dpg-d914js6gvqtc73a0kt60-a.oregon-postgres.render.com:5432/phishing_detector_181j
spring.datasource.username=phishing_detector_181j_user
spring.datasource.password=grWVFsqC75jlDibC5ofTayI4vHZHoio8
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true